Update resources.json
OctobearHub/octobear.org pull request #40
Opened 2022-10-06 17:18 UTC by Monodeep-Das

2022-10-06 18:51 UTC, TenTraicion approved these changes

2022-10-07 15:53 UTC, Monodeep-Das commented
Hey @TenTraicion can you please accept my PR

2022-10-07 20:15 UTC, clebsonf requested changes
Hi @Monodeep-Das, how are you? Looking around, I realized that we already had this resource. Unfortunately, I won't be able to accept your pull request, but if you wish, you can create another one with some other resource.

2022-10-07 20:15 UTC, clebsonf commented on src/assets/data/resources.json
> +        "title": "Iconic Pack",
duplicate resource https://github.com/OctobearHub/octobear.org/blob/12e90b79cd9533f4c7c8c0b7b078c0eb7a2a625a/src/assets/data/resources.json#L10-L13

2022-10-16 13:54 UTC, TenTraicion commented
@Monodeep-Das, it's been 9 days since we requested a change. Since there are no activities and reply from you we are closing this PR. You are welcome to add another resource and open a new PR. Thanks.

2022-10-16 13:54 UTC, closed without merging